# примеры API-запросов

@baseUrl = http://localhost:8000/api
###
# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ee4fe5adb2580e68fd0cdbcfa377865fb30cf37e


{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###
DELETE {{baseUrl}}/advertisements/40/
Authorization: Token ee4fe5adb2580e68fd0cdbcfa377865fb30cf37e

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/32/
Content-Type: application/json
Authorization: Token ee4fe5adb2580e68fd0cdbcfa377865fb30cf37e

{
  "status": "DRAFT"
}

###

PATCH {{baseUrl}}/advertisements/32/
Content-Type: application/json
Authorization: Token ee4fe5adb2580e68fd0cdbcfa377865fb30cf37e

{
  "title": "NEW_TITLE"
}

###


# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-11-23
Content-Type: application/json


###
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json
Authorization: Token 8bfab11d7419a7dcd334ddffbc786bf15ed82aac
