
# примеры API-запросов

@baseUrl = http://localhost:8000/api
###
# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP35",
  "description": "Десткая"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
    "name": "ESP31",
    "descriptions": "Вернул в гостинную!"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor_id": 3,
  "measure": 27.9
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json
